// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_U4cANMz8M1eU7WyYQUch9c4-diZ9CaQ',
    appId: '1:985912496116:web:be56dd719ce94c468373a1',
    messagingSenderId: '985912496116',
    projectId: 'test-614cc',
    authDomain: 'test-614cc.firebaseapp.com',
    storageBucket: 'test-614cc.firebasestorage.app',
    measurementId: 'G-2BDZLB5MDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBizjagIVdRxviZB09BNb9NVmB9KUEdNJw',
    appId: '1:985912496116:android:055c14b36443f1848373a1',
    messagingSenderId: '985912496116',
    projectId: 'test-614cc',
    storageBucket: 'test-614cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJsxReSXh3YXW_-wmmKNMUD6I2nRNL0Vo',
    appId: '1:985912496116:ios:0066eac6eea552138373a1',
    messagingSenderId: '985912496116',
    projectId: 'test-614cc',
    storageBucket: 'test-614cc.firebasestorage.app',
    iosBundleId: 'com.example.n2u',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJsxReSXh3YXW_-wmmKNMUD6I2nRNL0Vo',
    appId: '1:985912496116:ios:0066eac6eea552138373a1',
    messagingSenderId: '985912496116',
    projectId: 'test-614cc',
    storageBucket: 'test-614cc.firebasestorage.app',
    iosBundleId: 'com.example.n2u',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_U4cANMz8M1eU7WyYQUch9c4-diZ9CaQ',
    appId: '1:985912496116:web:a51a51054cf493c98373a1',
    messagingSenderId: '985912496116',
    projectId: 'test-614cc',
    authDomain: 'test-614cc.firebaseapp.com',
    storageBucket: 'test-614cc.firebasestorage.app',
    measurementId: 'G-LLXCS1T4DF',
  );
}
